### ISSUE TITLE
No compatibility with ESM

### ISSUE THREAD

**Issue by Calemy** [MaxOhn/rosu-pp-js#11]
Since the switch to wasm the compability with ESM faded, since it's now considered a commonjs only module. There is a workaround but i'd really wish to see native ESM back. Took me by surprise that my beatmap mirror just suddenly broke after upgrading packages lol

**Comment by MaxOhn** [comment]
Can you explain what you mean with "compability with ESM faded"? Using both the ES-, as well as the CommonJS way of importing works just fine for me so maybe you could share an MRE.

> Took me by surprise that my beatmap mirror just suddenly broke after upgrading packages lol

Given that the update bumped the version from 0.9 to 1.0, you should very much expect that there were various breaking changes. Check out https://semver.org/ for more info on semantic versioning.

**Comment by Calemy** [comment]
oh, i do expect braking changes. just the ESM thing caught me offguard. Also, it turns out that i've been a bit dumb. Since some classes got removed/changed my import simply error'd out. The error message from node was just a bit misleading. I apologize for that tho. While we're already here, do you think it's possible to support an array of accuracies to calculate multiple accuracies without having to rebuild the object?

**Comment by MaxOhn** [comment]
Glad you figured out the initial issue :)

> While we're already here, do you think it's possible to support an array of accuracies to calculate multiple accuracies without having to rebuild the object?

Definitely not a fan of being able to pass lists because then it wouldn't make sense to not also do it for other arguments, at which point the returned type would be an exponentially nested list. And even if only accuracies would be passable as list, that would either mean the calculation sometimes returns a single object and sometimes a list of objects which, or that it would always return a list even if accuracy wasn't specified as list; don't like either.

I do agree though that rebuilding a calculator object for each accuracy seems unnecessary. The best way to improve that in my mind is to use setters to re-use the same calculator but just set a different accuracy each time. Am a little surprised I didn't already add those setters, especially considering that they're available in the python binding already. Will open an issue and try to work on it soon 👍

**Comment by MaxOhn** [comment]
> The best way to improve that in my mind is to use setters to re-use the same calculator but just set a different accuracy each time.

Published through https://github.com/MaxOhn/rosu-pp-js/pull/14 in `v1.1.0` 🎉
